### ISSUE TITLE
Calling functions with wrapping the current applet throws NullPointerException

### ISSUE THREAD

**Issue by shengsword** [quil/quil#300] opened 2019-04-20 08:37 UTC
`(quil.applet/with-applet my-project
  (repeat 10 (q/random-gaussian)))` works fine

` (quil.applet/with-applet my-project
  (repeatedly 10 q/random-gaussian))
` throws **NullPointerException   quil.core/random-gaussian (core.cljc:3075)**

I must did something wrong...

**Comment by nbeloglazov** [comment] 2019-04-21 22:46
The error you are seeing is caused by clojure lazy evaluation. In the first example `(repeat 10 (q/random-gaussian))` you call `(q/random-gaussian)` eagerly, while applet is bound to `my-project` and then `repeat` returns a lazy sequence of the same already-evaluated value.

In the second example when you call `(repeatedly 10 q/random-gaussian)` - it returns a lazy sequence without calling `random-gaussian`. By the time the sequence will be evaluated - the applet will no longer be bound to `my-project` and will be bound to `null` instead. One way to fix it is to eagerly evaluate sequence using `doall` before returning it:

```clojure
(quil.applet/with-applet my-project
  (doall (repeatedly 10 q/random-gaussian))
```

Here is pure clojure example of the issue:

```clojure
(def ^:dynamic *foo* 5)
(defn get-foo [] *foo*)

(repeatedly 10 get-foo) ; => (5 5 5 5 5 5 5 5 5 5)

(binding [*foo* 7] (repeatedly 10 get-foo)) ;  => (5 5 5 5 5 5 5 5 5 5)

(binding [*foo* 7] (doall (repeatedly 10 get-foo))) ; => (7 7 7 7 7 7 7 7 7 7)
```

Hope this explains the issue. I'll close this bug, feel free to reopen if you have more questions.

**Closed by nbeloglazov** 2019-04-21 22:46 UTC
