### ISSUE TITLE
quil.core/background-image scales image by 50%

### ISSUE THREAD

**Issue by happy-lisper** [quil/quil#202] opened 2017-02-13 01:24 UTC
With version 2.4.0, quil.core/background-image does not work correctly on (at least OSX 10.11.6 and 1.8.0_102-b14). Same code works just fine in 2.3.0 and before.

excerpt from project.clj:

:dependencies [[org.clojure/clojure "1.8.0"]
                 [quil "2.4.0"]]

**Comment by nbeloglazov** [comment] 2017-02-13 01:44
Hi Andy

Can you provide code to reproduce the problem? Also have you tried the latest version 2.6.0?

**Comment by coreasync** [comment] 2017-02-16 02:21
Hi,
The repo is here https://github.com/coreasync/resize . Yes, I tried 2.6.0 and there is no difference.

This is what I see https://github.com/coreasync/resize/blob/master/actual.png were as in 2.3.0 I am getting this https://github.com/coreasync/resize/blob/master/with2.3.0.png

It could be other way around, that something got fixes in 2.4.0 though. However, it is still weird that I specify `:size [220 220]` which matches size of https://github.com/coreasync/resize/blob/master/clojure.png yet it does not cover all the background.

Best,
Andy

**Comment by nbeloglazov** [comment] 2017-02-27 07:43
Hi Andy. 

Thanks so much for providing project to reproduce it and sorry for the delay. I finally borrowed a mac and tested and as I suspected it's due to retina display. In version 2.4.0 I decided that it would be a good idea to change display density from 1 to whatever current screen has: https://github.com/quil/quil/blob/master/src/clj/quil/applet.clj#L204 Probably it wasn't such a good idea after all. I'm still not sure to be honest.

Anyway, to fix you problem you can set [pixel density](http://quil.info/api/environment#pixel-density) back to 1 in `:settings` function and it'll fix it:

```clojure
q/defsketch resize
  :title "You spin my circle right round"
  :size [220 220]
  :setup setup
  :settings #(q/pixel-density 1)
  :draw draw-state
  :features [:keep-on-top]
  :middleware [m/fun-mode])
```

I'll keep this bug open until I decide if I should remove auto-detection for pixel dencity.

**Comment by amonks** [comment] 2018-02-12 01:56
This behavior just confused the heck out of me.

The [graphics example](https://github.com/quil/quil-examples/blob/master/src/quil_sketches/graphics.clj) looks like this on my macbook:

<img width="612" alt="screen shot 2018-02-11 at 5 53 44 pm" src="https://user-images.githubusercontent.com/50010/36081503-a1f95dfa-0f54-11e8-8864-72893c24995e.png">

**Comment by nbeloglazov** [comment] 2018-04-01 06:11
Removed automatic pixel density setting. Closing this bug.

**Closed by nbeloglazov** 2018-04-01 06:11 UTC
