### ISSUE TITLE
Problems using mask

### ISSUE THREAD

**Issue by kchair** [quil/quil#207] opened 2017-04-24 01:07 UTC
Hello, I am having some problems applying a masking using image-mask. I've uploaded my code here: https://github.com/kchair/mysketch

The problem I have is the following error, when I try to run the sketch:

```bash
(<--
  session    "fecba207-1643-449a-879c-f832443f6b21"
  time-stamp "2017-04-23 18:01:56.157275000"
  out        "Exception in  :draw  function:  #error {
 :cause The PImage used with mask() must be the same size as the applet.
 :via
 [{:type java.lang.RuntimeException
   :message The PImage used with mask() must be the same size as the applet.
   :at [processing.opengl.PGraphicsOpenGL mask PGraphicsOpenGL.java 6068]}]
 :trace
 [[processing.opengl.PGraphicsOpenGL mask PGraphicsOpenGL.java 6068]
  [quil.core$mask_image invokeStatic core.cljc 2491]
  [quil.core$mask_image invoke core.cljc 2471]
  [quil.core$mask_image invokeStatic core.cljc 2490]
  [quil.core$mask_image invoke core.cljc 2471]
  [mysketch.core$draw_state$fn__11210 invoke core.clj 23]
  [mysketch.core$draw_state invokeStatic core.clj 21]
  [mysketch.core$draw_state invoke core.clj 14]
  [clojure.lang.Var invoke Var.java 379]
  [quil.middlewares.fun_mode$wrap_draw_update$quil_draw__11008 invoke fun_mode.cljc 16]
  [quil.middlewares.safe_fns$wrap_fn$fn__114 invoke safe_fns.clj 9]
  [quil.middlewares.bind_output$bind_output$iter__148__152$fn__153$fn__164 invoke"
)
```

I checked the docs and made sure my code is using the same image sizes as well as the p3d renderer. Any tips? Thank you

**Comment by kchair** [comment] 2017-04-24 02:44
Down-grading to quil 2.3.0 seems to solve this issue for me.

**Comment by nbeloglazov** [comment] 2017-05-07 00:53
Tried locally and worked fine. Are you using mackbook with retina display? I think this might be the cause: on retina "size" of applet internally is 2x which doesn't match the image. Can you try adding `pixel-density` as described [here](https://github.com/quil/quil/issues/202#issuecomment-282649108). Also it matches the fact that it worked for you on 2.3.0 as we switched pixel-density detection to automatic starting 2.4.0.

**Comment by nbeloglazov** [comment] 2017-10-28 19:54
Closing this bug. If you have any questions - feel free to reopen.

**Closed by nbeloglazov** 2017-10-28 19:54 UTC
