### ISSUE TITLE
Alpha ignored and blended colors turn white in clojurescript when using :p3d renderer

### ISSUE THREAD

**Issue by Jickelsen** [quil/quil#156] opened 2015-05-18 22:18 UTC
When supplying an alpha value to e.g. fill, the resulting shape is still rendered with no transparency whatsoever. This happens in clojurescript when using the :p3d renderer. When I attempted to use blend-color (with the :blend parameter) to achieve a similar effect the result was a completely white color.

Is this a known limitation of the :p3d renderer i ClojureScript? My sketch is just in 2D but I've noticed a drastic performance advantage over :p2d when sketch sizes are 1024x768 or larger, so I'd prefer to use it.

There seems to be an old issue with alpha in processing related to smoothing, but adjusting the smoothing value does not seem to affect this issue.

**Comment by nbeloglazov** [comment] 2015-05-19 04:55
Can you provide an example? 
I have feeling that the answer will be "it is limitation of processing.js" which quil uses under the hood.

**Comment by Jickelsen** [comment] 2015-05-19 08:16
Here's a repo with an example project
https://github.com/Jickelsen/blending

**Comment by nbeloglazov** [comment] 2015-05-27 06:08
`blend-color` was indeed broken! Thanks for clear and concise reproducible test case, it was helpful. 

As for transparency - looks like we pass transparency to processing js all the way down to WebGL calls, but for some reason it doesn't work. I'd say it's something to do with processing js. Also saw this post: https://groups.google.com/forum/#!topic/processingjs/h2y2Aph89E4 Seems like other people having troubles with transparency in 3D too.

**Comment by nbeloglazov** [comment] 2015-05-27 06:10
Closing the issue. If you have any other questions/ideas - feel free to reopen.

**Closed by nbeloglazov** 2015-05-27 06:10 UTC

**Comment by nbeloglazov** [comment] 2015-05-30 05:59
I pushed to clojars version 2.2.6-SNAPSHOT which contains the fix.

**Comment by Jickelsen** [comment] 2015-06-02 16:28
I haven't had time to try this out yet, but that's great! Thank you for tracking the bug down.

Quil in cljs only supports the two rendering modes p2d and p3d, right? What is the reason for not including the other ones available in processing.js, such as opengl? I am just assuming there is some meaningful difference between them.

**Comment by Norgat** [comment] 2015-06-02 16:47
> I am just assuming there is some meaningful difference between them.

It does not matter (as far as I understand Processing.js code). Because if you check https://github.com/processing-js/processing-js/blob/master/src/Processing.js (be careful! a lot of code!) for ```Drawing3D.prototype.size``` you can't find something different than

```
function getGLContext(canvas) {
          var ctxNames = ['experimental-webgl', 'webgl', 'webkit-3d'],
              gl;

          for (var i=0, l=ctxNames.length; i<l; i++) {
            gl = canvas.getContext(ctxNames[i], {antialias: false, preserveDrawingBuffer: true});
            if (gl) {
              break;
            }
          }

          return gl;
        }
```

for initializing context of canvas element for 3D drawing mode. Therefore is no difference between ```p3d``` and ```opengl``` modes for Processing.js.

I think this is just the inheritance from Java version of Processing.

**Comment by GoToLoop** [comment] 2015-06-02 18:48
http://forum.processing.org/two/discussion/comment/43979/#Comment_43979
